<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>f3a9a5d4-731b-4214-a36b-02b993ec3415</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.evg-btn-dismissal.evg-style-text.evg-light-on-dark.evg-position-text.evg-skip-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='evg-homepage-popup']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Close Popup&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>be0f0310-4815-4526-8583-0a39610c2353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>evg-btn-dismissal evg-style-text evg-light-on-dark evg-position-text evg-skip-top</value>
      <webElementGuid>5aaa9ea8-fca9-454c-965b-620e20630742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close Popup</value>
      <webElementGuid>5aa3cdb0-7ed2-4699-8365-6d21db6130af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9df717de-c2c4-468c-9b4b-3926efa62f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>5b4193e7-593b-46d1-ae83-1d1fa1ec1551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;evg-homepage-popup&quot;)/div[@class=&quot;evg-popup evg-style-bg web&quot;]/div[@class=&quot;evg-btn-dismissal evg-style-text evg-light-on-dark evg-position-text evg-skip-top&quot;]</value>
      <webElementGuid>191ca1d6-d300-43fa-b22c-f108e5a55e19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='evg-homepage-popup']/div[2]/div</value>
      <webElementGuid>6ce57445-22c5-41d6-928b-acc09cff2b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temukan Kami'])[1]/following::div[5]</value>
      <webElementGuid>61e8a031-12a3-429a-806d-8e95775b3b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>f232275b-6ef9-4aeb-805b-a07e688136bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>6b53d6c9-1473-4202-8d36-389828508181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '×' or . = '×')]</value>
      <webElementGuid>4f3857e0-5ada-4e21-a523-aed307ca40d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
