<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>99017827-21d1-4c9e-9664-a4ec682dbf5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.evg-btn-dismissal.evg-style-text.evg-light-on-dark.evg-position-text.evg-skip-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='evg-homepage-popup']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Close Popup&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b24a023b-e52c-4ec6-8e03-8810f55241fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>evg-btn-dismissal evg-style-text evg-light-on-dark evg-position-text evg-skip-top</value>
      <webElementGuid>6ea16978-9c89-4c66-832a-64e4289dfb99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close Popup</value>
      <webElementGuid>635b316a-dd54-40eb-9159-5fb1df819f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d6fae7e1-e8ed-4789-9df6-f71f8d7aab5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>765ee733-4ed5-4f36-99cf-fc14e4520ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;evg-homepage-popup&quot;)/div[@class=&quot;evg-popup evg-style-bg web&quot;]/div[@class=&quot;evg-btn-dismissal evg-style-text evg-light-on-dark evg-position-text evg-skip-top&quot;]</value>
      <webElementGuid>5f95c266-71ab-4d49-84fd-64b4315ef817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='evg-homepage-popup']/div[2]/div</value>
      <webElementGuid>5a91babd-3044-4cf5-af11-dc982357f92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temukan Kami'])[1]/following::div[5]</value>
      <webElementGuid>6671ba05-95fe-4daf-b0e8-8672f77f7dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>13544aec-8e48-4834-b6b7-e2813ebb5d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>adeafa93-c444-49d4-8ad9-7e94dcc702b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '×' or . = '×')]</value>
      <webElementGuid>0a2c0e33-7529-4916-a8ce-d6fe9d8aa53a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
