<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Akun Saya</name>
   <tag></tag>
   <elementGuidId>5ce330b7-49c4-40fe-bef3-810c5718d948</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div[3]/div/div[2]/div/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Akun Saya&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>78a9683a-b424-4859-b819-6b04983fad2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>qa-akun-submenu</value>
      <webElementGuid>b7d7e862-2715-4838-9bdc-34f6a2f0aa91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tracking-[0.03em] text-sm</value>
      <webElementGuid>7ec0a7fd-88a0-4ff6-af59-7152c4475891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akun Saya</value>
      <webElementGuid>7ed9c3d9-0222-45d6-a2be-8f4a7c5f2205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full right-0 left-0 fixed z-50&quot;]/div[@class=&quot;w-full right-0 left-0 bg-[rgba(0,0,0,0.4)] top-[108px] h-screen fixed z-30 cursor-default&quot;]/div[@class=&quot;w-full max-w-[1440px] mx-auto px-16 flex&quot;]/div[@class=&quot;w-[300px] bg-white opacity-100 flex flex-col gap-5 p-4 z-20 rounded-lg&quot;]/div[1]/div[@class=&quot;w-full flex&quot;]/a[@class=&quot;hover:bg-primary-light w-full px-4 py-2 rounded-sm&quot;]/span[@class=&quot;tracking-[0.03em] text-sm&quot;]</value>
      <webElementGuid>fc84ca47-e3fb-420d-8168-701273f10776</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[3]/div/div[2]/div/div/a/span</value>
      <webElementGuid>60777a44-97d2-4bfb-9308-cc7436c73792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crew'])[1]/following::span[1]</value>
      <webElementGuid>450f929f-76b9-4b5f-9494-65be8fd1f9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Luthfi Rahmat'])[1]/following::span[4]</value>
      <webElementGuid>ae7f8be1-1f7c-41b7-976a-db553380d3b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaksi'])[2]/preceding::span[1]</value>
      <webElementGuid>4ff9b9fe-04ce-4a14-9f0c-25ab8be17532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ulasan'])[1]/preceding::span[2]</value>
      <webElementGuid>ea7ed7ff-359f-4a3b-aebc-12c85d4fafe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Akun Saya']/parent::*</value>
      <webElementGuid>b9e2e29c-3e70-48b5-a6bf-ca048fc63076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/span</value>
      <webElementGuid>f0fbff30-4562-4c14-bdcf-79cc4e72854f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Akun Saya' or . = 'Akun Saya')]</value>
      <webElementGuid>08ae1cac-99e3-4829-9500-37e0b44de329</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
