<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Akun</name>
   <tag></tag>
   <elementGuidId>cef56eb3-5cfc-451d-b80b-5636dfd51860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mcis-header-middle']/div/div[3]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Akun&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>51f371fd-6201-427d-85b1-5852e79c0699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>qa-button-textakun</value>
      <webElementGuid>3aade69c-06c6-4493-a1dd-8cd3b2b0d4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tracking-[0.03em] text-sm font-bold text-white py-3 pr-1</value>
      <webElementGuid>78b623b0-3594-4615-91a0-8961b0442009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akun</value>
      <webElementGuid>5b20a6cd-6ac7-4a16-bccc-b882f073d765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mcis-header-middle&quot;)/div[@class=&quot;w-full max-w-[1440px] mx-auto px-16 flex h-[60px]&quot;]/div[@class=&quot;w-[550px] flex items-center gap-5 pt-4 pl-5 justify-end&quot;]/button[@class=&quot;focus:outline-none flex&quot;]/span[@class=&quot;tracking-[0.03em] text-sm font-bold text-white py-3 pr-1&quot;]</value>
      <webElementGuid>d78a731a-6c70-4851-9367-6729754bc226</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mcis-header-middle']/div/div[3]/button/span</value>
      <webElementGuid>5234d336-0649-4ca6-9ad5-c625d9f2e666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[2]/following::span[1]</value>
      <webElementGuid>20a040ce-ad63-43b6-9afe-8166027be0b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berbagai promo dan informasi bisa kamu temukan di sini.'])[1]/following::span[4]</value>
      <webElementGuid>fcae9721-85c9-4de1-b640-ce97170488d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/preceding::span[1]</value>
      <webElementGuid>7d94ff31-74ac-4086-a4cb-7b441cb66d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktifkan lokasimu untuk melihat toko terdekat'])[1]/preceding::span[2]</value>
      <webElementGuid>af968de9-081c-4a30-886e-9f94826a7488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Akun']/parent::*</value>
      <webElementGuid>7616501b-e81d-40a3-bd03-5689d2298bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span</value>
      <webElementGuid>2c3dcbcb-898c-4133-90d3-3c15956e63f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Akun' or . = 'Akun')]</value>
      <webElementGuid>74fcd298-4835-4c67-9daa-ed20ae7c416b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
